import Head from "next/head";
import Image from "next/image";
import { Footer } from "../Components/Footer";
import { Header } from "../Components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>N's PortForio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			{/* <Image src="/main-picture-1.jpg" layout="fill" /> */}

			<main className={styles.main} class="">
				<section class="bg-purple-200 w-full h-2/4">
					<h1 class="text-6xl">Profile</h1>
					<div class="text-4xl">
						<h3>Name: Naoki Hayashida</h3>
						<h3>19 years old</h3>
						<h3>From: Yokohama,Japan</h3>
					</div>
				</section>

				<section class="bg-blue-100">
					<h1>技術紹介</h1>
					<div>
						<div>
							<h2>HTML</h2>
						</div>
						<div>
							<h2>CSS</h2>
						</div>
						<div>
							<h2>Javascrpt</h2>
						</div>
						<div>
							<h2>React</h2>
						</div>
						<div>
							<h2>Tailwind css</h2>
						</div>
					</div>
				</section>

				<section>
					<h1>Contact</h1>
				</section>
			</main>
			<Footer />
		</div>
	);
}
