import Head from "next/head";
import Image from "next/image";
import { Footer } from "../Components/Footer";
import { Header } from "../Components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div class="font-serif h-screen flex flex-col">
			<Head>
				<title>N's PortForio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<main class="flex flex-col flex-1">
				<div class="bg-gray-100 w-full h-2/4 ">
					<h1 class="text-center text-6xl pt-10">Profile</h1>
					<div class="text-2xl pl-24 pt-14">
						<h3 class="py-1">Naoki Hayashida</h3>
						<h3 class="py-1">2002.05.09</h3>
						<h3 class="py-1">Yokohama,Japan</h3>
					</div>
				</div>

				<div class=" w-full h-3/5">
					<h1 class="text-6xl text-center pb-16 pt-10">Skill Set</h1>
					<div class=" py-8 flex flex-row content-center justify-center ">
						<div class="px-8">
							<Image
								src={"/HTML picture.png"}
								objectFit="contain"
								alt="HTML Picture"
								width="120px"
								height="120px"
							/>
							<h2 class="text-center">HTML</h2>
						</div>
						<div class="px-8">
							<Image
								src={"/CSS picture.png"}
								alt="CSS Picture"
								objectFit="contain"
								width="120px"
								height="120px"
							/>
							<h2 class="text-center">CSS</h2>
						</div>
						<div class="px-8">
							<Image
								src={"/Javascript .png"}
								alt="Javascript Picture"
								objectFit="contain"
								width="120px"
								height="120px"
							/>
							<h2 class="text-center">Javascrpt</h2>
						</div>
						<div class="px-8">
							<Image
								src={"/React Picture.png"}
								alt="React Picture"
								objectFit="contain"
								width="120px"
								height="120px"
							/>
							<h2 class="text-center">React</h2>
						</div>
						<div class="px-8">
							<Image
								src={"/Tailwindcss pic-2.png"}
								alt="Tailwindcss picture"
								objectFit="contain"
								width="120"
								height="120"
								class="items-center"
							/>
							<h2 class="text-center">Tailwind css</h2>
						</div>
					</div>
				</div>

				<div>
					<h1>Contact</h1>
				</div>
			</main>
			<Footer />
		</div>
	);
}
